### ISSUE TITLE
使用繁中翻譯製作DMP翻譯補丁/補全翻譯

### ISSUE THREAD

**Issue by Airtnp** [Ether1013/DuelMastersCardSearchTaiwan#1]
(全文由簡體轉換至繁體)

您好,

我是一名決鬥大師愛好者, 計劃收集並對照日文/英文(Duel Masters Fandom)/繁中翻譯(此repo)的效果文本,  通過GPT+RAG, 翻譯Duel Masters Play''s的效果到簡中/繁中和補全未翻譯的卡片效果.

請問您是否知曉繁中效果文本是誰人翻譯, 並是否可以得到其許可?

**Comment by Ether1013** [comment]
你好

網站「簡易決鬥王卡牌效果搜尋器」( ether1013.github.io/DuelMastersCardSearchTaiwan/index.html )
的作者即為在下我

除原始資料擷取有請他人協助之外
日翻中的部分皆是由我進行一人作業

在回答您的需求之前想先了解一下
個人的網站裡並沒有Duel Masters Play's的資料
即便遊戲跟實卡的資料大多相同
能力差距很多的卡牌也是大有卡在
為什麼會想要參考這個實卡資料彙集網站呢？

Ether 敬上
________________________________
寄件者: LR.X ***@***.***>
寄件日期: 2024年10月27日 上午 09:53
收件者: Ether1013/DuelMastersCardSearchTaiwan ***@***.***>
副本: Subscribed ***@***.***>
主旨: [Ether1013/DuelMastersCardSearchTaiwan] 使用繁中翻譯製作DMP翻譯補丁/補全翻譯 (Issue #1)


(全文由簡體轉換至繁體)

您好,

我是一名決鬥大師愛好者, 計劃收集並對照日文/英文(Duel Masters Fandom)/繁中翻譯(此repo)的效果文本, 通過GPT+RAG, 翻譯Duel Masters Play''s的效果到簡中/繁中和補全未翻譯的卡片效果.

請問您是否知曉繁中效果文本是誰人翻譯, 並是否可以得到其許可?

**Comment by Airtnp** [comment]
確實DMP中卡片效果與實卡有不同之處, 還有DMP專屬卡的存在, 但是仍然然可以使用GPT來對照翻譯, 我舉個還在測試的例子, 翻譯"S級原始 サンマックス"這張尚無翻譯的卡片:

GPT 提示詞: https://pastebin.com/Pd25cWCp

GPT 翻譯:

```plain
(K)進化(/K)－進化在戰鬥場上1隻費用3的我方自然文明生物之上。
(K)S級侵略原始－費用3的自然文明生物（我方費用3的自然文明生物攻擊時，可以將此生物從手牌或魔力區置於其上。）
若我方生物數量有3隻以上，則此生物獲得攻擊力+9000及(K)T・ブレイカー(/K)能力。
此生物在我方回合結束時，可以將其放入魔力區，若這樣做，則選擇1隻對方生物並將其置入其持有者的魔力區。
```

實然DMP更改了很多關鍵字效果, 但英文社區已有完備的英日翻譯對照和嵌入Unity方案: 

https://new.reddit.com/r/DuelMastersPlays/comments/1fe8mxu/how_to_translate_duel_masters_plays_with_bepinex/

**Comment by Ether1013** [comment]
了解

所以只是要使用我的翻譯內容去訓練AI
那我許可使用

不過我的原始資料都是有因應個人系統而上了客製化標籤
然後關鍵字的翻譯是做在另一個對照表裡面
你們在使用的時候要記得處理這些問題
不然會變成訓練雜訊喔

以上
Ether
________________________________
寄件者: LR.X ***@***.***>
寄件日期: 2024年10月28日 下午 04:05
收件者: Ether1013/DuelMastersCardSearchTaiwan ***@***.***>
副本: Ether1013 ***@***.***>; Comment ***@***.***>
主旨: Re: [Ether1013/DuelMastersCardSearchTaiwan] 使用繁中翻譯製作DMP翻譯補丁/補全翻譯 (Issue #1)


確實DMP中卡片效果與實卡有不同之處, 還有DMP專屬卡的存在, 但是仍然然可以使用GPT來對照翻譯, 我舉個還在測試的例子, 翻譯"S級原始 サンマックス"這張尚無翻譯的卡片:

GPT 提示詞: https://pastebin.com/Pd25cWCp

GPT 翻譯:

(K)進化(/K)－進化在戰鬥場上1隻費用3的我方自然文明生物之上。
(K)S級侵略原始－費用3的自然文明生物（我方費用3的自然文明生物攻擊時，可以將此生物從手牌或魔力區置於其上。）
若我方生物數量有3隻以上，則此生物獲得攻擊力+9000及(K)T・ブレイカー(/K)能力。
此生物在我方回合結束時，可以將其放入魔力區，若這樣做，則選擇1隻對方生物並將其置入其持有者的魔力區。


實然DMP更改了很多關鍵字效果, 但英文社區已有完備的英日翻譯對照和嵌入Unity方案:

https://new.reddit.com/r/DuelMastersPlays/comments/1fe8mxu/how_to_translate_duel_masters_plays_with_bepinex/

**Comment by Airtnp** [comment]
了解! 非常感謝!

**Comment by Ether1013** [comment]
你好

這邊想請教一下
您這邊目前的計畫是針對Play's進行卡牌效果日文轉英文、或是日文轉中文的AI自動翻譯對嗎？

請問如果訓練完成之後
是否能夠提供卡名的日←→英轉換API呢？


感謝
Ether 敬上
________________________________
寄件者: LR.X ***@***.***>
寄件日期: 2024年10月29日 上午 10:02
收件者: Ether1013/DuelMastersCardSearchTaiwan ***@***.***>
副本: Ether1013 ***@***.***>; Comment ***@***.***>
主旨: Re: [Ether1013/DuelMastersCardSearchTaiwan] 使用繁中翻譯製作DMP翻譯補丁/補全翻譯 (Issue #1)


Closed #1<https://github.com/Ether1013/DuelMastersCardSearchTaiwan/issues/1> as completed.

**Comment by Ether1013** [comment]
你好

不知道您那邊的訓練結束了沒
我這邊舊網站已經結束運作
改由新網站進行

如果想拿所有資料的話
請使用以下API串接：
https://duelmasterscardsearchtaiwan.onrender.com/api/v2/carddata

Ether
________________________________
寄件者: Zhuang Ether ***@***.***>
寄件日期: 2024年11月11日 上午 11:43
收件者: Ether1013/DuelMastersCardSearchTaiwan ***@***.***>
主旨: 回覆: [Ether1013/DuelMastersCardSearchTaiwan] 使用繁中翻譯製作DMP翻譯補丁/補全翻譯 (Issue #1)

你好

這邊想請教一下
您這邊目前的計畫是針對Play's進行卡牌效果日文轉英文、或是日文轉中文的AI自動翻譯對嗎？

請問如果訓練完成之後
是否能夠提供卡名的日←→英轉換API呢？


感謝
Ether 敬上
________________________________
寄件者: LR.X ***@***.***>
寄件日期: 2024年10月29日 上午 10:02
收件者: Ether1013/DuelMastersCardSearchTaiwan ***@***.***>
副本: Ether1013 ***@***.***>; Comment ***@***.***>
主旨: Re: [Ether1013/DuelMastersCardSearchTaiwan] 使用繁中翻譯製作DMP翻譯補丁/補全翻譯 (Issue #1)


Closed #1<https://github.com/Ether1013/DuelMastersCardSearchTaiwan/issues/1> as completed.
